### ISSUE TITLE
Increase the size of the numbers on image ?

### ISSUE THREAD

**Issue by Valexandre** [cj-holmes/paintr#1]
First of all thanks for that package. I think my 4 y old daughter will love it !
How could I increase the size of the numbers on the image ? 
I don't quite manage to make them readable, I can change the size of the legend but not of the inside text itself!

Thanks !

**Comment by cj-holmes** [comment]
Hi! There is an argument `number_size` which you can increase (default is 0.5) - I hope that works for you

**Comment by Valexandre** [comment]
Thanks ! It does. I close this issue and open another one !
